public class Creature extends Card {
    enum CREATURE_TYPE {
        ANGEL, SOLDIER, HUMAN, DRUID, ELF, DRAGON, CONSTRUCT, WIZARD, CAT, WARRIOR, ELDER, LORD, MERFOLK, KITHKIN, DINOSAUR, CLERIC, VAMPIRE, ZOMBIE,
        SKELETON, BEAST, ALLY, AETHERBORN, ASSASSIN, ARCHER, ADVISOR, BAT, BEAR, BIRD, BLINKMOTH, CENTUAR, CITIZEN, COWARD, CRAB, CROCODILE, CYCLOPS, CEPHALID,
        DEVIL, DEMON, DRONE, DRYAD, DWARF, DREADNOUGHT, DESERTER, COCKATRICE, CARRIER, CARIBOU, CAMARID, BEEBLE, BASILISK, ARCHON, ASSEMBLY_WORKER, ATOG, ARTIFICER, AUROCHS, AVATAR, ANTELOPE, ANTEATER, BADGER, BARBARIAN, DRAKE, DJINN, ELDRAZI, EFREET, ELK, ELEPHANT, ELEMENTAL, FAERIE, FROG, FLAGBEARER,  GARGOYLE, FUNGUS, FISH, GERM, GIANT, GOBLIN, GOAT, GOLEM,
        GORGON, GRAVEBORN, GRIFFIN, GREMLIN, GOD, GNOME, HARPY, HELLION, HORMARID, HOMUNCULUS, HORROR, HORSE, HOUND, HYDRA, HYENA, ILLUSION, IMP, INSECT, JELLYFISH,
        JUGGERNAUT, KAVU, KNIGHT, KOR, KRAKEN, KOBOLD, LEECH, LEVIATHAN, LHURGOYF, LICID, LIZARD, MERCENARY, MINION, MINOTAUR, MOLE, MONGER, MONGOOSE, MONK, MOONFOLK,
        MUTANT, MYR, MYSTIC, NAGA, NINJA, NOMAD, NYMPH, NEPHILIM, NIGHTMARE, OCTOPUS, OGRE, OOZE, ORB, ORC,  OUPHE, OX, OYSTER, PEGASUS, PENTATITE, PEST, PHOENIX,
        PIRATE, PLANT, PRAETOR, PRISM, PROCESSOR, RABBIT, RAT, REBEL, RHINO, RIGGER, ROGUE, SAlAMANDER, SAMURAI, SAND, SAPROLING, SATYR, SCION, SCORPION, SCOUT, SERF,
        SERPENT, SHADE, SHAPESHIFTER, SHEEP, SIREN, SLIVER, SLUG, SNAKE, SPAWN, SPECTER, SPHINX, SPIDER, SPIKE, SPIRIT, SPONGE, SQUID, SQUIRREL, STARFISH, SURRAKAR,
        SURVIVOR, THALAKOS, THOPTER, THRULL, TREEFOLK, TRISKELAVITE, TROLL, TUTRTLE, UNICORN, VEDALKEN, VIASHINO, WALL, WEIRD, WEREWOLF, WHALE, WOLF, WOLVERINE,
        WOMBAT, WORM, WRAITH, WURM, YETI, SABLE;
    }

    enum KEYWORD_ABILITIES {
        FLYING, HEXPROOF, HASTE, SHROUD, VIGILANCE, FIRST_STRIKE, DOUBLE_STRIKE, FEAR, DEATHTOUCH, LIFELINK, INFECT, PROWESS,  PERSIST, DEFENDER, FLASH,
        INDESTRUCTIBLE, MENACE, REACH, TRAMPLE, ANNIHILATOR, BANDING, BATTLE_CRY, CASCADE, CONVOKE, DEVOID, DELVE, DETHRONE, DREDGE, EXALTED, FLANKING, HORSEMASHIP,
        PHASING, RETRACE, REBOUND, SKULK, SHADOW, STORM, SPLIT_SECOND, UNDYING, WITHER;
    }

    private CREATURE_TYPE[] creature_types;
    private Integer power;
    private Integer toughness;
    private KEYWORD_ABILITIES[] keyword_abilities;

    Creature(String card_name, String mana_cost, RARITY rarity, CREATURE_TYPE[] creatureTypes) {
        super(card_name, CARD_TYPE.CREATURE, mana_cost, rarity);
        this.creature_types = creatureTypes;
    }

    public Integer getPower() {
        return this.power;
    }

    public Integer getToughness() {
        return this.toughness;
    }

    public void setPower(Integer newPower) {
        this.power = newPower;
    }

    public void setToughness(Integer newToughness) {
        this.toughness = newToughness;
    }

    public KEYWORD_ABILITIES[] getKeywordAbilities() {
        return this.keyword_abilities;
    }

    public void setKeywordAbilities(KEYWORD_ABILITIES[] newKeywordAbilities) {
        this.keyword_abilities = newKeywordAbilities;
    }
}
